// TODO: start to generate code like this with a script!
export const SET_USER_INFO = 'SET_USER_INFO';
export const REMOVE_USER_INTO = 'REMOVE_USER_INTO';
export const FETCH_MERGE_FIELDS = 'FETCH_MERGE_FIELDS';
export const FETCH_MERGE_FIELDS_SUCCESS = 'FETCH_MERGE_FIELDS_SUCCESS';
export const UPDATE_MERGE_FIELD = 'UPDATE_MERGE_FIELD';
export const SUBMIT_MERGE_FIELDS = 'SUBMIT_MERGE_FIELDS';
export const SUBMIT_MERGE_FIELDS_SUCCESS = 'SUBMIT_MERGE_FIELDS_SUCCESS;'